# Generated by Django 4.2.4 on 2023-09-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skillucketApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucketskill",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userskill",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
