# Generated by Django 4.2.4 on 2023-09-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillucketApp', '0003_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Tell the world about yourself!'),
        ),
    ]
